name: progressofttask
description: "ProgressSoft Application Development Task In Flutter Framework."
# By Mustafa Hassoneh
# https://github.com/mustafa-707
# https://www.linkedin.com/in/is10vmust/

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: "3.19.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # state
  flutter_hooks: ^0.20.5
  flutter_bloc: ^8.1.6

  # look and feel
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  top_snackbar_flutter: ^3.1.0
  country_code_helper: ^0.1.0 # https://github.com/mustafa-707/flutter_country_code.git
  modal_bottom_sheet: ^3.0.0
  pin_input_text_field: ^4.5.1

  # network and serilization
  http: ^1.2.1
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  otp_autofill: ^3.0.2

  # utils and services
  intl: 0.18.1 # TODO : flutter upgrade
  shared_preferences: ^2.2.3
  bcrypt: ^1.1.3

  # firebase
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: 2.4.9 # TODO : flutter upgrade
  freezed: 2.5.2 # TODO : flutter upgrade
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#FBFBFB"
  android_12:
    color: "#FBFBFB"
flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/logo/fgi.png"
  image_path_ios: "assets/logo/foreground_logo.png"
  adaptive_icon_background: "#FBFBFB"
  adaptive_icon_foreground: "assets/logo/fgi.png"

flutter:
  uses-material-design: true
  # run this to generate a Freezed Models : flutter pub run build_runner build --delete-conflicting-outputs
  generate: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/icons/navbar/

  # Google Fonts : https://fonts.google.com/specimen/IBM+Plex+Sans
  fonts:
    - family: IBMPlexSans-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
    - family: IBMPlexSansArabic-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
    - family: IBMPlexSansArabic-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf

# prevent accidental publishing to pub.dev using `pub publish`
publish_to: "none"
