// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgNfcbDaRq31N7hmZDh68fUulKOzkqL2I',
    appId: '1:922771085182:android:c9c395313120b5def2c52f',
    messagingSenderId: '922771085182',
    projectId: 'progressofttask',
    storageBucket: 'progressofttask.appspot.com',
    androidClientId: '922771085182-97s0m0uifirkifv3a8u0e91r103up29o.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyY9RG5922aypFihEqB9RHHpy5VaHRwxE',
    appId: '1:922771085182:ios:cd11d3c2a6c59a78f2c52f',
    messagingSenderId: '922771085182',
    projectId: 'progressofttask',
    storageBucket: 'progressofttask.appspot.com',
    iosClientId: '922771085182-pvncdjg19lthkrbg07qgcf1qe88vqon3.apps.googleusercontent.com',
    iosBundleId: 'com.example.progressofttask',
  );
}
